Bicep/module 02
percebus/azure-secure-networking-for-devs pull request #48
Opened 2024-11-26 23:02 UTC by jessica-ern

Refactored learning module 01 into more bicep modules for easier reading (sorry for the overloaded term)

Added bicep for learning module 02.

My idea was that learning module 02 would have all the same bicep from module 01 with more added (and then 03 would be all of 02 with more added).  The alternative could be to have learning module 2 reference everything from 01 as existing resources. Let me know what you think

2024-11-26 23:03 UTC, jessica-ern commented on bicep/02/modules/firewall.bicep
> +        name: 'allow-github'
The 'deny-all' rule is redundant, the default is to always deny all.  let me know if you want me to add the redundant rule anyway

2024-11-27 16:58 UTC, percebus commented on bicep/02/modules/bastion.bicep
> +}
I see some resources are identical, like `bastion`

![image](https://github.com/user-attachments/assets/edd5148c-8041-4557-89b2-d7e29ae21e43)

Is copying the module "best practice" when it comes to bicep scripts?
How might we avoid duplication?

Some thoughts

1. Have `02/main.bicep` point to `../01/modules/bastion.bicep`
1.  Create symlinks?
1. Other workaround?

2024-11-27 17:00 UTC, percebus commented on bicep/02/modules/firewall.bicep
> +resource firewallPolicy 'Microsoft.Network/firewallPolicies@2024-03-01' = {
[Unlike `bastion`](https://github.com/percebus/azure-secure-networking-for-devs/pull/48/files#r1860998846), since this resource extends upon `firewall` from `01/modules/firewall`, it makes sense to me to duplicate the file

![image](https://github.com/user-attachments/assets/ea64053a-9a53-4f18-b223-c6b667b385bc)

2024-11-27 17:01 UTC, percebus commented on bicep/02/modules/hubVNet.bicep
> +}
should everything `routeTable` be its own file?

2024-11-27 17:06 UTC, percebus commented on bicep/02/modules/hubVNet.bicep
> +}
Nitpick?

Seems like this `defaultSubnet` alias for `default` subnet could be created as part of `01`

![image](https://github.com/user-attachments/assets/58f90a98-15c6-4575-a394-20cd49a61be5)

2024-11-27 17:09 UTC, percebus commented on bicep/02/main.bicep
> +    // addresses start at 10.1.0.0
"Code never lies, comments sometime do"

I believe the `default` ** is under `10.1.4.0/22`, which is `10.1.4-7.x`

2024-11-27 17:13 UTC, percebus requested changes
Added some comments here and there about how we could prevent duplication?

2024-11-27 17:13 UTC, percebus commented on bicep/02/modules/spokeVNet.bicep
> +output vNetId string = spokeVNet.id
[Same comment as bastion](https://github.com/percebus/azure-secure-networking-for-devs/pull/48/files#r1860998846)

2024-11-27 17:13 UTC, percebus commented on bicep/02/modules/vNetPeering.bicep
> +}
[Same comment as bastion](https://github.com/percebus/azure-secure-networking-for-devs/pull/48/files#r1860998846)

2024-11-27 17:28 UTC, percebus commented on bicep/02/main.bicep
> +    // addresses start at 10.1.0.0
Nevermind, this is the `hub` vnet, I was thrown by the `jumpBox` stuff, but that is just params

2024-12-02 16:23 UTC, percebus commented on bicep/02/modules/firewall.bicep
> +        name: 'allow-github'
I think the tutorial uses "Rules (classic)"

![image](https://github.com/user-attachments/assets/a97e8b3b-f52b-4b7e-9056-cf9f5be736d3)

Whereas your bicep scripts seem to be leveraging the newer "Policies"

![image](https://github.com/user-attachments/assets/a59125dc-4c57-4ebb-86c2-017d3e43ab13)

2024-12-02 16:43 UTC, jessica-ern commented on bicep/02/modules/firewall.bicep
> +        name: 'allow-github'
I couldn't get the DNS filtering setting to work without using policies in bicep.  Would you like me to add some comments to the bicep about how this differs from the manual tutorial?

As for the original comment, I thought deny-all was also the default for the classic rules?

2024-12-02 16:48 UTC, jessica-ern commented on bicep/02/modules/bastion.bicep
> +}
This is what I was getting at in the PR description. I don't think I can reference the module 01 bicep files as existing resources because we had to make changes to those existing resources (like firewall).

Otherwise it would be a design choice. Do we want the modules to behave like one complete bicep project with 4 groups of resources or do we want them to behave as 4 snapshots of a project, 04 being the final complete project. (but I don't think that first option is complete available to me due to updating existing resources between modules)

2024-12-02 16:55 UTC, jessica-ern commented on bicep/02/modules/hubVNet.bicep
> +}
but the alias is only needed in 02 for the vm nic.  If I put that in 01 the linter would probably be made about an unuseed reference

2024-12-02 17:48 UTC, percebus approved these changes

2024-12-02 18:52 UTC, jessica-ern commented on bicep/02/modules/spokeVNet.bicep
> +output vNetId string = spokeVNet.id
addressed in https://github.com/percebus/azure-secure-networking-for-devs/pull/48#discussion_r1866216282

2024-12-02 18:52 UTC, jessica-ern commented on bicep/02/modules/vNetPeering.bicep
> +}
addressed in https://github.com/percebus/azure-secure-networking-for-devs/pull/48#discussion_r1866216282

2024-12-02 18:57 UTC, jessica-ern commented on bicep/02/modules/firewall.bicep
> +        name: 'allow-github'
@percebus I don't have the access to your project board to do this, but I think to resolve this comment, we should add a backlog item to do one of the following:

1. try harder to get DNS to work with classic rules in bicep, maybe I missed something
2. downgrade the bicep versions of the resource? that might unlock the DNS setting with classic rules
4. update the manual steps to the "new" way using policies, since classic rules is the "old" way anyway

2024-12-02 18:58 UTC, merged